BikeStoreWebApp/BikeStoreWebApp/Controllers/BicycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Sql;
using System.Data.SqlClient;
using System.Configuration;
using BikeStoreWebApp.Models;
using BikeStoreWebApp_Database;

namespace BikeStoreWebApp.Controllers
{
    public class BicycleController : Controller
    {
        // GET: Bicycle
        [Route]
        public ActionResult Store()
        {
            var category = new List<StoreHome>
            {
                new StoreHome { categoryID = 1, categoryName = "Mountain Bicycles", categoryImage = "~/Images/patriotmountain.jpg" },
                new StoreHome { categoryID = 2, categoryName = "Road Bicycles", categoryImage = "~/Images/cinelliroad.jpg" },
                new StoreHome { categoryID = 3, categoryName = "Touring Bicycles", categoryImage = "~/Images/cannontouring.jpg"}
            };

            return View(category);
        }

        [Route("{id:int}")]
        public ActionResult Listing(int id)
        {
            BikeStoreWebApp.Models.BicycleListing bicycle = new BikeStoreWebApp.Models.BicycleListing();

            var listing = new List<spGetProductsbySubcategoryID_Result>();

            var item = bicycle.GetBicyclesForListing(id);

            foreach (spGetProductsbySubcategoryID_Result product in item)
            { 
                listing.Add(product);
            }

            return View(listing);
        }

        [Route("{id:int}")]
        public ActionResult Description(int id)
        {
            BikeStoreWebApp.Models.BicycleDescription bicycle = new BikeStoreWebApp.Models.BicycleDescription();

            var description = new List<spGetProductDetails_Result>();
            var item = bicycle.GetBicycleDetailForDescription(id);
            foreach (spGetProductDetails_Result product in item)
            {
                description.Add(product);
            }

            return View(description);
        }

        [Route]
        public ActionResult Cart()
        {
            return View();
        }

        [Route]
        public ActionResult Checkout()
        {
            return View();
        }

        [Route]
        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

BikeStoreWebApp/BikeStoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bikes R Us</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <!--<![endif]-->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/base-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.27?/css/layouts/marketing.css">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bikes R Us", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bicycles", "Store", "Bicycle")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year IST 440W - Team 1</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN1tm--BsRPNJL2RVo1Dy6ZXlL30CGyAQ"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

BikeStoreWebApp/BikeStoreWebApp/Views/Shared/_Store.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bikes R Us</title>
    @Styles.Render("~/Content/css")

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <!--<![endif]-->
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/base-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://purecss.io/combo/1.17.27?/css/layouts/marketing.css">
</head>
<body>
    <div class="header">
        <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal">
            <div class="pure-menu-heading">
                @Html.ActionLink("Bikes R Us", "Index", "Home")
            </div>
            <ul>
                <li>@Html.ActionLink("Bicycles", "Store", "Bicycle")</li>
                <li>@Html.ActionLink("Touring", "Listing", "Bicycle", new { id = 3 })</li>
                <li>@Html.ActionLink("Mountain", "Listing", "Bicycle", new { id = 1 })</li>
                <li>@Html.ActionLink("Road", "Listing", "Bicycle", new { id = 2 })</li>
                <li>@Html.ActionLink("Cart", "Cart", "Bicycle")</li>
                <li class="pure-menu-selected">
                    @Html.ActionLink("Login", "Login", "Account")
                </li>            
            </ul>
        </div>
    </div>

    
    @RenderBody()
  
    
    <div class="footer l-box is-center">
        <p>&copy; @DateTime.Now.Year IST 440W - Team 1</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>